apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
spec:
  config:
    add_linkerd_headers: true
    enable_grpc_web: true
    x_forwarded_proto_redirect: false
    use_remote_address: false
    cors:
      origins: "*"
      methods: GET, PUT, DELETE, POST, OPTIONS
      headers: |
        x-atmz-version, keep-alive, user-agent, cache-control, content-type, cookie,
        content-transfer-encoding, Authorization, Device, Platform, OS, Browser, x-ip,
        x-accept-content-transfer-encoding, x-accept-response-streaming, x-user-agent,
        x-grpc-web, grpc-timeout, x-signature, x-signatures, mfa-id, mfa-code, x-nonce,
        correlationid, recaptcha-token
      exposed_headers: grpc-status,grpc-message,correlationid
      credentials: true
      max_age: "1728000"
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: wildcard
spec:
  hostname: "*"
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Route
  selector:
    matchLabels:
      hostname: wildcard
